from skin import Skin

market = [
    Skin("Karambit Gold", "Nameless", "Nameless", "Regular", 150000),
    Skin("AWM Treasure Hunter", "Nameless", "Nameless", "Regular", 110000),
    Skin("AWM Sport V2", "Nameless", "Nameless", "Regular", 80000),
    Skin("USP Genesis", "Nameless", "Nameless", "Regular", 55000),
    Skin("G22", "Nameless", "Nameless", "Regular", 38000),
    Skin("AKR Treasure Hunter", "Arcane", "Origin", "Stattrack", 80000),
    Skin("AKR Treasure Hunter", "Arcane", "Origin", "Regular", 8400),
    Skin("M9 Bayonet Dragon Glass", "Arcane", "Origin", "Knife", 62000),
    Skin("M9 Bayonet Scratch", "Arcane", "Origin", "Knife", 43000),
    Skin("M9 Bayonet Universe", "Arcane", "Origin", "Knife", 38000),
    Skin("M9 Bayonet Ancient", "Arcane", "Origin", "Knife", 11000),
    Skin("G22 NEST", "Arcane", "Origin", "Stattrack", 7400),
    Skin("G22 NEST", "Arcane", "Origin", "Regular", 1000),
    Skin("AKR 12 Railgun", "Legendary", "Origin", "Stattrack", 15000),
    Skin("AKR 12 Railgun", "Legendary", "Origin", "Regular", 1200),
    Skin("M16 Winged", "Legendary", "Origin", "Stattrack", 14000),
    Skin("M16 Winged", "Legendary", "Origin", "Regular", 1400),
    Skin("M4 Necromancer", "Legendary", "Origin", "Stattrack", 14100),
    Skin("M4 Necromancer", "Legendary", "Origin", "Regular", 1400),
    Skin("P90 Ghoul", "Epic", "Origin", "Stattrack", 3400),
    Skin("P90 Ghoul", "Epic", "Origin", "Regular", 300),
    Skin("P350 Neon", "Epic", "Origin", "Stattrack", 3250),
    Skin("P350 Neon", "Epic", "Origin", "Regular", 300),
    Skin("UMP45 Cyberpunk", "Epic", "Origin", "Stattrack", 2900),
    Skin("UMP45 Cyberpunk", "Epic", "Origin", "Regular", 307),
    Skin("Desert Eagle Predator", "Rare", "Origin", "Stattrack", 670),
    Skin("Desert Eagle Predator", "Rare", "Origin", "Regular", 100),
    Skin("SM1014 Pathfiender", "Rare", "Origin", "Stattrack", 620),
    Skin("SM1014 Pathfiender", "Rare", "Origin", "Regular", 100),
    Skin("AKR12 Pixel Camouflage", "Rare", "Origin", "Regular", 94),
    Skin("AKR12 Pixel Camouflage", "Rare", "Origin", "Stattrack", 640),
    Skin("AWM Phoenix", "Rare", "Origin", "Regular", 92),
    Skin("AWM Phoenix", "Rare", "Origin", "Stattrack", 640),
]
